version: '3.7'

services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:12.2
    ports:
      - '5432:5432'
    env_file:
      - ./.private/postgres.env
  api:
    container_name: backend
    restart: always
    build: .
    ports:
      - '8000:8000'
    volumes:
      - ./:/usr/src/api/
    entrypoint: /usr/src/api/scripts/docker_script.sh