version: '3.7'

services:
  api:
    container_name: backend
    restart: always
    build: .
    ports:
      - '8000:5000'
    volumes:
      - ./:/usr/src/api/
    depends_on: 
      - postgres
    entrypoint: /usr/src/api//scripts/docker_script.sh
  postgres:
    container_name: postgres
    restart: always
    image: postgres:12.2
    ports:
      - '5432:5432'
    env_file:
      - ./.private/postgres.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  
volumes: 
  postgres_data:
    name: postgres_data